# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounce',
            name='image',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
